# Provider configuration for the BTC Indexer.
# Set CONFIG_FILE env var to point to this file (default: ./config/provider-config.yaml).

platform:
  url: https://myaccount.myinstance.kaleido.io/
  timeout: 120000
  auth:
    username: myuser
    password: my-api-key

providerName: bitcoin-indexer
providerMetadata:
  displayName: BTC Indexer
  description: Indexes BTC Transfer events into the Kaleido Asset Manager

environmentNameOrId: my-bitcoin-env

assetManagerNameOrId: my-asset-manager

connectorNameOrId: my-bitcoin-connector

workflowEngineNameOrId: workflow-engine

# BTC contract to index
config:
  bulkQueryLimit: 100 # when retrieving fragments/addresses to build a picture of spends to inform the update
  upsertTriggerCount: 100 # the amount of individual objects to trigger an upsert
  networkName: testnet4
  networkId: 0x283f161c
  tokenSymbol: tBTC
  tokenName: testnet4-btc

stream:
  autoCreate: true
  factory: transactionEvents
  name: btc-indexer
  eventSourceConfig:
    unfiltered: true
    fromBlock: '0'
    batchSize: 5 # the number of transactions to collect from the blockchain
    batchTimeout: '10s'
    pollTimeout: '30s'
    requiredConfirmations: 5
