// Copyright © 2026 Kaleido, Inc.
//
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


/**
 * Internationalization for SDK error messages.
 *
 * Error codes follow the pattern: KA1406XX
 * - KA: Kaleido prefix , 
 * - 140: SDK error category
 * - 6: SDK subcategory
 * - XX: Specific error number
 */

export interface ErrorMessage {
  code: string;
  message: string;
}

/**
 * Create a formatted error with code and message
 */
function fe(code: string, template: string): ErrorMessage {
  return { code, message: template };
}

/**
 * SDK error messages
 */
export const SDKErrors = {
  // Handler errors (KA1406XX)
  MsgSDKObservedPanic: fe('KA140600', 'Observed panic: %s'),
  MsgSDKUnknownHandler: fe('KA140601', "Unknown handler '%s'"),
  MsgSDKUnknownNoListenerConfig: fe('KA140602', "Listener config for stream '%s' not supplied by workflow engine"),
  MsgSDKOutputSerializationError: fe('KA140603', "Unable to serialize output to %s"),
  MsgSDKDirectorNextStageMissing: fe('KA140604', "Handler called with 'nextStage' missing from input"),
  MsgSDKDirectorOutputPathMissing: fe('KA140605', "Handler called with 'outputPath' missing from input"),
  MsgSDKDirectorFailureStageMissing: fe('KA140606', "Handler resulted in a failure, but 'failureStage' missing from input"),
  MsgSDKInputParsingError: fe('KA140607', 'Unable to parse input'),
  MsgSDKInvalidAction: fe('KA140608', "Action '%s' is invalid for handler '%s'"),
  MsgSDKInvalidResult: fe('KA140609', "Action '%s' gave unexpected result '%s' without error"),

  // Event source errors
  MsgSDKCheckpointInvalidForHandler: fe('KA140610', "Checkpoint could not be parsed by handler '%s'"),
  MsgSDKStreamConfigInvalidForHandler: fe('KA140611', "Event stream config could not be parsed by handler '%s'"),
  MsgSDKCheckpointInvalid: fe('KA140612', "Checkpoint generated by handler '%s' cannot be serialized"),
  MsgSDKEventSourceDataInvalid: fe('KA140613', "Event source data could not be serialized for handler '%s'"),

  // Engine API errors
  MsgSDKEngineReplyInvalidData: fe('KA140614', "Engine API reply for transaction %s invalid: %s"),
  MsgSDKEngineReplyInvalidType: fe('KA140615', "Engine API reply type for transaction %s invalid: %s"),
  MsgSDKEngineReqNoActiveRequest: fe('KA140616', 'No engine handler is active on the supplied context'),
  MsgSDKEngineFailMarshalEngineRequest: fe('KA140617', 'Failed to marshal engine transaction data'),
  MsgSDKEngineFailSendEngineRequest: fe('KA140618', 'Failed to send engine transaction'),
  MsgSDKEngineNoTokenAuthRef: fe('KA140619', "No auth token available in engine supplied context for authRef '%s'"),

  // Configuration errors
  MsgSDKProviderNameNotSet: fe('KA140620', 'Provider name not set'),
  MsgSDKURLRequiredOutbound: fe('KA140630', 'URL is required in outbound mode'),
  MsgSDKWebSocketPortRequiredInbound: fe('KA140631', 'WEBSOCKET_PORT is required in inbound mode'),
  MsgSDKAccountNotSet: fe('KA140632', 'ACCOUNT is not set and no baseUrl provided'),
  MsgSDKEnvironmentNotSet: fe('KA140633', 'ENVIRONMENT is not set and no baseUrl provided'),
  MsgSDKWorkflowEngineNotSet: fe('KA140634', 'WORKFLOW_ENGINE is not set and no baseUrl provided'),

  // Stage Director errors
  MsgSDKHandlerNotConfigured: fe('KA140621', 'Handler not configured for this action'),
  MsgSDKBatchHandlerNotConfigured: fe('KA140622', 'Handler not configured for BATCH invocation mode'),
  MsgSDKBatchHandlerResultCountMismatch: fe('KA140623', 'Batch handler returned %d results but expected %d'),
  MsgSDKInputNullOrUndefined: fe('KA140628', 'Input is null or undefined in stage %s'),
  MsgSDKMissingActionField: fe('KA140629', 'Input is missing required "action" field in stage %s. Available fields: %s'),

  // Configuration validation errors
  MsgSDKConfigUnknownAuthType: fe('KA140626', 'Unknown auth type: %s'),

  // Engine connection errors
  MsgSDKEngineNotConnected: fe('KA140627', 'WebSocket is not connected. Cannot submit async transactions'),
} as const;

/**
 * Format an error message with arguments
 * Supports simple %s, %d placeholders
 */
export function formatError(errorMsg: ErrorMessage, ...args: any[]): string {
  let formatted = errorMsg.message;

  for (const arg of args) {
    // Replace first occurrence of %s or %d
    formatted = formatted.replace(/%[sd]/, String(arg));
  }

  return `${errorMsg.code}: ${formatted}`;
}

/**
 * Create a new Error with an i18n message
 */
export function newError(errorMsg: ErrorMessage, ...args: any[]): Error {
  return new Error(formatError(errorMsg, ...args));
}

