name: Core SDK CI

on:
  pull_request:
    paths:
      - 'packages/core-sdk/**'
      - '.github/workflows/ci-core-sdk.yaml'

permissions:
  contents: read

jobs:
  core-sdk:
    name: Build and Test (Core SDK)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/core-sdk
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - run: npm install

      - run: npm run build

      - run: npm test
